opt_in_rules:
  - empty_count
  - empty_string
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - prohibited_super_call
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - PUChallengeTests

line_length: 140